/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/_dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/_dashboard/index'
import { Route as PasswordResetUidTokenRouteImport } from './routes/password-reset.$uid.$token'
import { Route as AuthenticatedLogsSearchVehicleRouteImport } from './routes/_authenticated/logs/search-vehicle'
import { Route as AuthenticatedDashboardVehiclesIndexRouteImport } from './routes/_authenticated/_dashboard/vehicles/index'
import { Route as AuthenticatedDashboardUsersIndexRouteImport } from './routes/_authenticated/_dashboard/users/index'
import { Route as AuthenticatedDashboardPermissionsIndexRouteImport } from './routes/_authenticated/_dashboard/permissions/index'
import { Route as AuthenticatedDashboardMembershipsIndexRouteImport } from './routes/_authenticated/_dashboard/memberships/index'
import { Route as AuthenticatedLogsCreateVehiclesIdRouteImport } from './routes/_authenticated/logs/create/$vehiclesId'
import { Route as AuthenticatedDashboardVehiclesVehiclesIdRouteImport } from './routes/_authenticated/_dashboard/vehicles/$vehiclesId'
import { Route as AuthenticatedDashboardUsersUserIdRouteImport } from './routes/_authenticated/_dashboard/users/$userId'
import { Route as AuthenticatedDashboardPermissionsGroupIdRouteImport } from './routes/_authenticated/_dashboard/permissions/$groupId'
import { Route as AuthenticatedDashboardMembershipsMembershipIdRouteImport } from './routes/_authenticated/_dashboard/memberships/$membershipId'
import { Route as AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRouteImport } from './routes/_authenticated/_dashboard/vehicles/$vehiclesId/log/$logId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const PasswordResetUidTokenRoute = PasswordResetUidTokenRouteImport.update({
  id: '/password-reset/$uid/$token',
  path: '/password-reset/$uid/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLogsSearchVehicleRoute =
  AuthenticatedLogsSearchVehicleRouteImport.update({
    id: '/logs/search-vehicle',
    path: '/logs/search-vehicle',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardVehiclesIndexRoute =
  AuthenticatedDashboardVehiclesIndexRouteImport.update({
    id: '/vehicles/',
    path: '/vehicles/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUsersIndexRoute =
  AuthenticatedDashboardUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPermissionsIndexRoute =
  AuthenticatedDashboardPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMembershipsIndexRoute =
  AuthenticatedDashboardMembershipsIndexRouteImport.update({
    id: '/memberships/',
    path: '/memberships/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedLogsCreateVehiclesIdRoute =
  AuthenticatedLogsCreateVehiclesIdRouteImport.update({
    id: '/logs/create/$vehiclesId',
    path: '/logs/create/$vehiclesId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardVehiclesVehiclesIdRoute =
  AuthenticatedDashboardVehiclesVehiclesIdRouteImport.update({
    id: '/vehicles/$vehiclesId',
    path: '/vehicles/$vehiclesId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUsersUserIdRoute =
  AuthenticatedDashboardUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPermissionsGroupIdRoute =
  AuthenticatedDashboardPermissionsGroupIdRouteImport.update({
    id: '/permissions/$groupId',
    path: '/permissions/$groupId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMembershipsMembershipIdRoute =
  AuthenticatedDashboardMembershipsMembershipIdRouteImport.update({
    id: '/memberships/$membershipId',
    path: '/memberships/$membershipId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRoute =
  AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRouteImport.update({
    id: '/log/$logId',
    path: '/log/$logId',
    getParentRoute: () => AuthenticatedDashboardVehiclesVehiclesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedDashboardIndexRoute
  '/about': typeof AboutRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/logs/search-vehicle': typeof AuthenticatedLogsSearchVehicleRoute
  '/password-reset/$uid/$token': typeof PasswordResetUidTokenRoute
  '/memberships/$membershipId': typeof AuthenticatedDashboardMembershipsMembershipIdRoute
  '/permissions/$groupId': typeof AuthenticatedDashboardPermissionsGroupIdRoute
  '/users/$userId': typeof AuthenticatedDashboardUsersUserIdRoute
  '/vehicles/$vehiclesId': typeof AuthenticatedDashboardVehiclesVehiclesIdRouteWithChildren
  '/logs/create/$vehiclesId': typeof AuthenticatedLogsCreateVehiclesIdRoute
  '/memberships/': typeof AuthenticatedDashboardMembershipsIndexRoute
  '/permissions/': typeof AuthenticatedDashboardPermissionsIndexRoute
  '/users/': typeof AuthenticatedDashboardUsersIndexRoute
  '/vehicles/': typeof AuthenticatedDashboardVehiclesIndexRoute
  '/vehicles/$vehiclesId/log/$logId': typeof AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedDashboardIndexRoute
  '/about': typeof AboutRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/logs/search-vehicle': typeof AuthenticatedLogsSearchVehicleRoute
  '/password-reset/$uid/$token': typeof PasswordResetUidTokenRoute
  '/memberships/$membershipId': typeof AuthenticatedDashboardMembershipsMembershipIdRoute
  '/permissions/$groupId': typeof AuthenticatedDashboardPermissionsGroupIdRoute
  '/users/$userId': typeof AuthenticatedDashboardUsersUserIdRoute
  '/vehicles/$vehiclesId': typeof AuthenticatedDashboardVehiclesVehiclesIdRouteWithChildren
  '/logs/create/$vehiclesId': typeof AuthenticatedLogsCreateVehiclesIdRoute
  '/memberships': typeof AuthenticatedDashboardMembershipsIndexRoute
  '/permissions': typeof AuthenticatedDashboardPermissionsIndexRoute
  '/users': typeof AuthenticatedDashboardUsersIndexRoute
  '/vehicles': typeof AuthenticatedDashboardVehiclesIndexRoute
  '/vehicles/$vehiclesId/log/$logId': typeof AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_authenticated/logs/search-vehicle': typeof AuthenticatedLogsSearchVehicleRoute
  '/password-reset/$uid/$token': typeof PasswordResetUidTokenRoute
  '/_authenticated/_dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/_dashboard/memberships/$membershipId': typeof AuthenticatedDashboardMembershipsMembershipIdRoute
  '/_authenticated/_dashboard/permissions/$groupId': typeof AuthenticatedDashboardPermissionsGroupIdRoute
  '/_authenticated/_dashboard/users/$userId': typeof AuthenticatedDashboardUsersUserIdRoute
  '/_authenticated/_dashboard/vehicles/$vehiclesId': typeof AuthenticatedDashboardVehiclesVehiclesIdRouteWithChildren
  '/_authenticated/logs/create/$vehiclesId': typeof AuthenticatedLogsCreateVehiclesIdRoute
  '/_authenticated/_dashboard/memberships/': typeof AuthenticatedDashboardMembershipsIndexRoute
  '/_authenticated/_dashboard/permissions/': typeof AuthenticatedDashboardPermissionsIndexRoute
  '/_authenticated/_dashboard/users/': typeof AuthenticatedDashboardUsersIndexRoute
  '/_authenticated/_dashboard/vehicles/': typeof AuthenticatedDashboardVehiclesIndexRoute
  '/_authenticated/_dashboard/vehicles/$vehiclesId/log/$logId': typeof AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accept-invitation'
    | '/login'
    | '/reset-password'
    | '/account'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/logs/search-vehicle'
    | '/password-reset/$uid/$token'
    | '/memberships/$membershipId'
    | '/permissions/$groupId'
    | '/users/$userId'
    | '/vehicles/$vehiclesId'
    | '/logs/create/$vehiclesId'
    | '/memberships/'
    | '/permissions/'
    | '/users/'
    | '/vehicles/'
    | '/vehicles/$vehiclesId/log/$logId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accept-invitation'
    | '/login'
    | '/reset-password'
    | '/account'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/logs/search-vehicle'
    | '/password-reset/$uid/$token'
    | '/memberships/$membershipId'
    | '/permissions/$groupId'
    | '/users/$userId'
    | '/vehicles/$vehiclesId'
    | '/logs/create/$vehiclesId'
    | '/memberships'
    | '/permissions'
    | '/users'
    | '/vehicles'
    | '/vehicles/$vehiclesId/log/$logId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/about'
    | '/accept-invitation'
    | '/login'
    | '/reset-password'
    | '/_authenticated/_dashboard'
    | '/_authenticated/account'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/_authenticated/logs/search-vehicle'
    | '/password-reset/$uid/$token'
    | '/_authenticated/_dashboard/'
    | '/_authenticated/_dashboard/memberships/$membershipId'
    | '/_authenticated/_dashboard/permissions/$groupId'
    | '/_authenticated/_dashboard/users/$userId'
    | '/_authenticated/_dashboard/vehicles/$vehiclesId'
    | '/_authenticated/logs/create/$vehiclesId'
    | '/_authenticated/_dashboard/memberships/'
    | '/_authenticated/_dashboard/permissions/'
    | '/_authenticated/_dashboard/users/'
    | '/_authenticated/_dashboard/vehicles/'
    | '/_authenticated/_dashboard/vehicles/$vehiclesId/log/$logId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  PasswordResetUidTokenRoute: typeof PasswordResetUidTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard': {
      id: '/_authenticated/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard/': {
      id: '/_authenticated/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/password-reset/$uid/$token': {
      id: '/password-reset/$uid/$token'
      path: '/password-reset/$uid/$token'
      fullPath: '/password-reset/$uid/$token'
      preLoaderRoute: typeof PasswordResetUidTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/logs/search-vehicle': {
      id: '/_authenticated/logs/search-vehicle'
      path: '/logs/search-vehicle'
      fullPath: '/logs/search-vehicle'
      preLoaderRoute: typeof AuthenticatedLogsSearchVehicleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard/vehicles/': {
      id: '/_authenticated/_dashboard/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof AuthenticatedDashboardVehiclesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/users/': {
      id: '/_authenticated/_dashboard/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedDashboardUsersIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/permissions/': {
      id: '/_authenticated/_dashboard/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof AuthenticatedDashboardPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/memberships/': {
      id: '/_authenticated/_dashboard/memberships/'
      path: '/memberships'
      fullPath: '/memberships/'
      preLoaderRoute: typeof AuthenticatedDashboardMembershipsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/logs/create/$vehiclesId': {
      id: '/_authenticated/logs/create/$vehiclesId'
      path: '/logs/create/$vehiclesId'
      fullPath: '/logs/create/$vehiclesId'
      preLoaderRoute: typeof AuthenticatedLogsCreateVehiclesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard/vehicles/$vehiclesId': {
      id: '/_authenticated/_dashboard/vehicles/$vehiclesId'
      path: '/vehicles/$vehiclesId'
      fullPath: '/vehicles/$vehiclesId'
      preLoaderRoute: typeof AuthenticatedDashboardVehiclesVehiclesIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/users/$userId': {
      id: '/_authenticated/_dashboard/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedDashboardUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/permissions/$groupId': {
      id: '/_authenticated/_dashboard/permissions/$groupId'
      path: '/permissions/$groupId'
      fullPath: '/permissions/$groupId'
      preLoaderRoute: typeof AuthenticatedDashboardPermissionsGroupIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/memberships/$membershipId': {
      id: '/_authenticated/_dashboard/memberships/$membershipId'
      path: '/memberships/$membershipId'
      fullPath: '/memberships/$membershipId'
      preLoaderRoute: typeof AuthenticatedDashboardMembershipsMembershipIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/vehicles/$vehiclesId/log/$logId': {
      id: '/_authenticated/_dashboard/vehicles/$vehiclesId/log/$logId'
      path: '/log/$logId'
      fullPath: '/vehicles/$vehiclesId/log/$logId'
      preLoaderRoute: typeof AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRouteImport
      parentRoute: typeof AuthenticatedDashboardVehiclesVehiclesIdRoute
    }
  }
}

interface AuthenticatedDashboardVehiclesVehiclesIdRouteChildren {
  AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRoute: typeof AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRoute
}

const AuthenticatedDashboardVehiclesVehiclesIdRouteChildren: AuthenticatedDashboardVehiclesVehiclesIdRouteChildren =
  {
    AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRoute:
      AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRoute,
  }

const AuthenticatedDashboardVehiclesVehiclesIdRouteWithChildren =
  AuthenticatedDashboardVehiclesVehiclesIdRoute._addFileChildren(
    AuthenticatedDashboardVehiclesVehiclesIdRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardMembershipsMembershipIdRoute: typeof AuthenticatedDashboardMembershipsMembershipIdRoute
  AuthenticatedDashboardPermissionsGroupIdRoute: typeof AuthenticatedDashboardPermissionsGroupIdRoute
  AuthenticatedDashboardUsersUserIdRoute: typeof AuthenticatedDashboardUsersUserIdRoute
  AuthenticatedDashboardVehiclesVehiclesIdRoute: typeof AuthenticatedDashboardVehiclesVehiclesIdRouteWithChildren
  AuthenticatedDashboardMembershipsIndexRoute: typeof AuthenticatedDashboardMembershipsIndexRoute
  AuthenticatedDashboardPermissionsIndexRoute: typeof AuthenticatedDashboardPermissionsIndexRoute
  AuthenticatedDashboardUsersIndexRoute: typeof AuthenticatedDashboardUsersIndexRoute
  AuthenticatedDashboardVehiclesIndexRoute: typeof AuthenticatedDashboardVehiclesIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardMembershipsMembershipIdRoute:
      AuthenticatedDashboardMembershipsMembershipIdRoute,
    AuthenticatedDashboardPermissionsGroupIdRoute:
      AuthenticatedDashboardPermissionsGroupIdRoute,
    AuthenticatedDashboardUsersUserIdRoute:
      AuthenticatedDashboardUsersUserIdRoute,
    AuthenticatedDashboardVehiclesVehiclesIdRoute:
      AuthenticatedDashboardVehiclesVehiclesIdRouteWithChildren,
    AuthenticatedDashboardMembershipsIndexRoute:
      AuthenticatedDashboardMembershipsIndexRoute,
    AuthenticatedDashboardPermissionsIndexRoute:
      AuthenticatedDashboardPermissionsIndexRoute,
    AuthenticatedDashboardUsersIndexRoute:
      AuthenticatedDashboardUsersIndexRoute,
    AuthenticatedDashboardVehiclesIndexRoute:
      AuthenticatedDashboardVehiclesIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedLogsSearchVehicleRoute: typeof AuthenticatedLogsSearchVehicleRoute
  AuthenticatedLogsCreateVehiclesIdRoute: typeof AuthenticatedLogsCreateVehiclesIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedLogsSearchVehicleRoute: AuthenticatedLogsSearchVehicleRoute,
  AuthenticatedLogsCreateVehiclesIdRoute:
    AuthenticatedLogsCreateVehiclesIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  PasswordResetUidTokenRoute: PasswordResetUidTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
