/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/_dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/_dashboard/index'
import { Route as AuthenticatedLogsSearchVehicleRouteImport } from './routes/_authenticated/logs/search-vehicle'
import { Route as AuthenticatedDashboardVehiclesIndexRouteImport } from './routes/_authenticated/_dashboard/vehicles/index'
import { Route as AuthenticatedLogsCreateVehiclesIdRouteImport } from './routes/_authenticated/logs/create/$vehiclesId'
import { Route as AuthenticatedDashboardVehiclesVehiclesIdRouteImport } from './routes/_authenticated/_dashboard/vehicles/$vehiclesId'
import { Route as AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRouteImport } from './routes/_authenticated/_dashboard/vehicles/$vehiclesId/log/$logId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedLogsSearchVehicleRoute =
  AuthenticatedLogsSearchVehicleRouteImport.update({
    id: '/logs/search-vehicle',
    path: '/logs/search-vehicle',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardVehiclesIndexRoute =
  AuthenticatedDashboardVehiclesIndexRouteImport.update({
    id: '/vehicles/',
    path: '/vehicles/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedLogsCreateVehiclesIdRoute =
  AuthenticatedLogsCreateVehiclesIdRouteImport.update({
    id: '/logs/create/$vehiclesId',
    path: '/logs/create/$vehiclesId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardVehiclesVehiclesIdRoute =
  AuthenticatedDashboardVehiclesVehiclesIdRouteImport.update({
    id: '/vehicles/$vehiclesId',
    path: '/vehicles/$vehiclesId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRoute =
  AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRouteImport.update({
    id: '/log/$logId',
    path: '/log/$logId',
    getParentRoute: () => AuthenticatedDashboardVehiclesVehiclesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedDashboardIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/logs/search-vehicle': typeof AuthenticatedLogsSearchVehicleRoute
  '/vehicles/$vehiclesId': typeof AuthenticatedDashboardVehiclesVehiclesIdRouteWithChildren
  '/logs/create/$vehiclesId': typeof AuthenticatedLogsCreateVehiclesIdRoute
  '/vehicles/': typeof AuthenticatedDashboardVehiclesIndexRoute
  '/vehicles/$vehiclesId/log/$logId': typeof AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedDashboardIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/logs/search-vehicle': typeof AuthenticatedLogsSearchVehicleRoute
  '/vehicles/$vehiclesId': typeof AuthenticatedDashboardVehiclesVehiclesIdRouteWithChildren
  '/logs/create/$vehiclesId': typeof AuthenticatedLogsCreateVehiclesIdRoute
  '/vehicles': typeof AuthenticatedDashboardVehiclesIndexRoute
  '/vehicles/$vehiclesId/log/$logId': typeof AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_authenticated/_dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_authenticated/logs/search-vehicle': typeof AuthenticatedLogsSearchVehicleRoute
  '/_authenticated/_dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/_dashboard/vehicles/$vehiclesId': typeof AuthenticatedDashboardVehiclesVehiclesIdRouteWithChildren
  '/_authenticated/logs/create/$vehiclesId': typeof AuthenticatedLogsCreateVehiclesIdRoute
  '/_authenticated/_dashboard/vehicles/': typeof AuthenticatedDashboardVehiclesIndexRoute
  '/_authenticated/_dashboard/vehicles/$vehiclesId/log/$logId': typeof AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/logs/search-vehicle'
    | '/vehicles/$vehiclesId'
    | '/logs/create/$vehiclesId'
    | '/vehicles/'
    | '/vehicles/$vehiclesId/log/$logId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/logs/search-vehicle'
    | '/vehicles/$vehiclesId'
    | '/logs/create/$vehiclesId'
    | '/vehicles'
    | '/vehicles/$vehiclesId/log/$logId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/_authenticated/_dashboard'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/_authenticated/logs/search-vehicle'
    | '/_authenticated/_dashboard/'
    | '/_authenticated/_dashboard/vehicles/$vehiclesId'
    | '/_authenticated/logs/create/$vehiclesId'
    | '/_authenticated/_dashboard/vehicles/'
    | '/_authenticated/_dashboard/vehicles/$vehiclesId/log/$logId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard': {
      id: '/_authenticated/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard/': {
      id: '/_authenticated/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/logs/search-vehicle': {
      id: '/_authenticated/logs/search-vehicle'
      path: '/logs/search-vehicle'
      fullPath: '/logs/search-vehicle'
      preLoaderRoute: typeof AuthenticatedLogsSearchVehicleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard/vehicles/': {
      id: '/_authenticated/_dashboard/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof AuthenticatedDashboardVehiclesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/logs/create/$vehiclesId': {
      id: '/_authenticated/logs/create/$vehiclesId'
      path: '/logs/create/$vehiclesId'
      fullPath: '/logs/create/$vehiclesId'
      preLoaderRoute: typeof AuthenticatedLogsCreateVehiclesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard/vehicles/$vehiclesId': {
      id: '/_authenticated/_dashboard/vehicles/$vehiclesId'
      path: '/vehicles/$vehiclesId'
      fullPath: '/vehicles/$vehiclesId'
      preLoaderRoute: typeof AuthenticatedDashboardVehiclesVehiclesIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/vehicles/$vehiclesId/log/$logId': {
      id: '/_authenticated/_dashboard/vehicles/$vehiclesId/log/$logId'
      path: '/log/$logId'
      fullPath: '/vehicles/$vehiclesId/log/$logId'
      preLoaderRoute: typeof AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRouteImport
      parentRoute: typeof AuthenticatedDashboardVehiclesVehiclesIdRoute
    }
  }
}

interface AuthenticatedDashboardVehiclesVehiclesIdRouteChildren {
  AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRoute: typeof AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRoute
}

const AuthenticatedDashboardVehiclesVehiclesIdRouteChildren: AuthenticatedDashboardVehiclesVehiclesIdRouteChildren =
  {
    AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRoute:
      AuthenticatedDashboardVehiclesVehiclesIdLogLogIdRoute,
  }

const AuthenticatedDashboardVehiclesVehiclesIdRouteWithChildren =
  AuthenticatedDashboardVehiclesVehiclesIdRoute._addFileChildren(
    AuthenticatedDashboardVehiclesVehiclesIdRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardVehiclesVehiclesIdRoute: typeof AuthenticatedDashboardVehiclesVehiclesIdRouteWithChildren
  AuthenticatedDashboardVehiclesIndexRoute: typeof AuthenticatedDashboardVehiclesIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardVehiclesVehiclesIdRoute:
      AuthenticatedDashboardVehiclesVehiclesIdRouteWithChildren,
    AuthenticatedDashboardVehiclesIndexRoute:
      AuthenticatedDashboardVehiclesIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedLogsSearchVehicleRoute: typeof AuthenticatedLogsSearchVehicleRoute
  AuthenticatedLogsCreateVehiclesIdRoute: typeof AuthenticatedLogsCreateVehiclesIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedLogsSearchVehicleRoute: AuthenticatedLogsSearchVehicleRoute,
  AuthenticatedLogsCreateVehiclesIdRoute:
    AuthenticatedLogsCreateVehiclesIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
